import Head from 'next/head';
import styles from '@/styles/Home.module.css';
// import About from '@/components/sections/about';
import About from '@/components/sections/about';
import Contact from '@/components/sections/contact';
import Experience from '@/components/sections/experience';
import Work from '@/components/sections/work';
import Navbar from '@/components/navbar';

export default function IndexPage() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar/>

      <main className={styles.main}>
          <About />
          {/* About component */}

          <Experience />
          {/* Experience component */}

          <Work />
          {/* Work component */}

        <Contact/>
          {/* contact component */}
      </main>
    </>
  );
}
